[package]
name = "robot-main"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grpc-server = { path = "../grpc-server"}
openvslam-wrap = { path = "../openvslam-wrap"}
