grpc_port = 50051

[detector]
enabled=true
model = "models/ikea3.tflite"
clustering_max_distance = 0.2
clustering_min_landmarks = 3
min_landmark_score = 4.0

[slam]
vocab = "slam/orb_vocab.fbow"
openvslam_config = "slam/slam.yaml"
enable_auto_slace_estimation = true
# mask = "slam/mask.png"
# map = "slam/map.db"

[navigation]
travel_thrust = 0.2
# thrust of the left and right wheels on turning right (turning left will be the same but reversed)
turn_right_thrust = [0.2, -0.1]
# the navigation goal is reached if the distance is less than this value (meters)
xy_goal_tolerance = 0.12
yaw_goal_tolerance = 0.3
