download-models:
	mkdir -p models && cd models \
	&& wget -O efficientdet-lite0-int8.tflite https://tfhub.dev/tensorflow/lite-model/efficientdet/lite0/detection/default/1?lite-format=tflite \
	&& wget -O efficientdet-lite1-int8.tflite https://tfhub.dev/tensorflow/lite-model/efficientdet/lite1/detection/default/1?lite-format=tflite \
	&& wget -O efficientdet-lite2-int8.tflite https://tfhub.dev/tensorflow/lite-model/efficientdet/lite2/detection/default/1?lite-format=tflite 
